std::string vertexShaderSource =
	"layout(location = 0) in vec3 v_Position;\n"
	"layout(location = 2) in vec2 v_TexCoord;\n"
	"\n"
	"out vec2 f_TexCoord;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_Position = vec4(v_Position * 2.0, 1.0);\n"
	"    f_TexCoord = v_TexCoord;\n"
	"}\n"
	"\n";
std::string fragmentShaderSource =
	"layout(location = 0) out vec4 f_FragColor;\n"
	"\n"
	"in vec2 f_TexCoord;\n"
	"\n"
	"uniform sampler2D frg_Texture;\n"
	"uniform sampler2D frg_BayerMatrix;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    vec4 color = texture(frg_Texture, f_TexCoord);\n"
	"    float bayer = texture(frg_BayerMatrix, gl_FragCoord.xy / 8.0).r * (255.0 / 64.0);\n"
	"    vec4 rgba = color * 255.0;\n"
	"    vec4 head = floor(rgba);\n"
	"    vec4 tail = rgba - head;\n"
	"    vec4 finalColor = head + step(bayer, tail);\n"
	"    f_FragColor = finalColor / 255.0;\n"
	"}\n";
